export const scenesData = [
  {
    id: "comic1",
    index: 1,
    title: "Aventura 1",
    path: "/lottiej/animacion1.json",
    nextRoute: "/comic/2",
    prevRoute: "/nuestro-comic",
  },
  {
    id: "comic2",
    index: 2,
    title: "Aventura 2",
    path: "/lottiej/animacion2.json",
    nextRoute: "/comic/3",
    prevRoute: "/comic/1",
  },
  {
    id: "comic3",
    index: 3,
    title: "Aventura 3",
    path: "/lottiej/animacion3.json",
    nextRoute: "/comic/4",
    prevRoute: "/comic/2",
  },
  {
    id: "comic4",
    index: 4,
    title: "Aventura 4",
    path: "/lottiej/animacion4.json",
    nextRoute: "/comic/5",
    prevRoute: "/comic/3",
  },
  {
    id: "comic5",
    index: 5,
    title: "Aventura 5",
    path: "/lottiej/animacion5.json",
    nextRoute: "/comic/6",
    prevRoute: "/comic/4",
  },
  {
    id: "comic6",
    index: 6,
    title: "Aventura 6",
    path: "/lottiej/animacion6.json",
    nextRoute: "/comic/7",
    prevRoute: "/comic/5",
  },
  {
    id: "comic7",
    index: 7,
    title: "Aventura 7",
    path: "/lottiej/animacion7.json",
    nextRoute: "/comic/8",
    prevRoute: "/comic/6",
  },
  {
    id: "comic8",
    index: 8,
    title: "Aventura 8",
    path: "/lottiej/animacion8.json",
    nextRoute: "/nuestro-comic",
    prevRoute: "/comic/7",
  },
];